// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in user's customers and vendors, optionally filtered by name or type.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filter by client name."),
    type: z.enum(["customer", "vendor", "both"]).optional().describe("Filter by party type."),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("clients").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) query = query.ilike("name", `%${search}%`);
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    return error ? fail(error.message) : ok(data ?? []);
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_invoices_default = defineTool2({
  name: "list_invoices",
  title: "List sales invoices",
  description: "List the signed-in user's sales invoices with number, client, totals, status and due date.",
  inputSchema: {
    status: z2.enum(["draft", "sent", "paid", "partial", "overdue", "cancelled"]).optional().describe("Filter by invoice status."),
    client_id: z2.string().uuid().optional().describe("Filter by client id."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("invoices").select(
      "id,number,client_id,status,net_total,subtotal,vat_total,due_date,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    if (client_id) query = query.eq("client_id", client_id);
    const { data, error } = await query;
    return error ? fail(error.message) : ok(data ?? []);
  }
});

// src/lib/mcp/tools/list-items.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_items_default = defineTool3({
  name: "list_items",
  title: "List inventory items",
  description: "List the signed-in user's inventory items with rate, cost and current stock.",
  inputSchema: {
    search: z3.string().trim().optional().describe("Filter by item name."),
    low_stock_only: z3.boolean().optional().describe("Only return items at or below their reorder level."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, low_stock_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("items").select("id,name,unit,rate,cost,stock,reorder_level,vat_percentage").order("name").limit(limit ?? 100);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return fail(error.message);
    const rows = low_stock_only ? (data ?? []).filter(
      (i) => i.reorder_level != null && Number(i.stock) <= Number(i.reorder_level)
    ) : data ?? [];
    return ok(rows);
  }
});

// src/lib/mcp/tools/list-vouchers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_vouchers_default = defineTool4({
  name: "list_vouchers",
  title: "List vouchers",
  description: "List the signed-in user's accounting vouchers (expense, contra, loan, journal) with amounts and narration.",
  inputSchema: {
    type: z4.enum(["contra", "expense", "loan_given", "loan_received", "journal"]).optional().describe("Filter by voucher type."),
    from_date: z4.string().optional().describe("Earliest voucher date (YYYY-MM-DD)."),
    to_date: z4.string().optional().describe("Latest voucher date (YYYY-MM-DD)."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("vouchers").select("id,number,type,date,party_name,amount,narration,method,reference").order("date", { ascending: false }).limit(limit ?? 50);
    if (type) query = query.eq("type", type);
    if (from_date) query = query.gte("date", from_date);
    if (to_date) query = query.lte("date", to_date);
    const { data, error } = await query;
    return error ? fail(error.message) : ok(data ?? []);
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^4.4.3";
var financial_summary_default = defineTool5({
  name: "financial_summary",
  title: "Financial summary",
  description: "Summarise the signed-in user's sales, purchases, payments received and outstanding receivables.",
  inputSchema: {
    from_date: z5.string().optional().describe("Start date (YYYY-MM-DD)."),
    to_date: z5.string().optional().describe("End date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const range = (q) => {
      let query = q;
      let out = query;
      if (from_date) out = out.gte("created_at", from_date);
      if (to_date) out = out.lte("created_at", to_date);
      return out;
    };
    const [sales, purchases, payments] = await Promise.all([
      range(supabase.from("invoices").select("net_total,status")),
      range(supabase.from("purchase_invoices").select("net_total,status")),
      range(supabase.from("payments").select("amount,invoice_type"))
    ]);
    const err = sales.error || purchases.error || payments.error;
    if (err) return fail(err.message);
    const sum = (rows, key) => rows.reduce((t, r) => t + Number(r[key] ?? 0), 0);
    const salesRows = sales.data ?? [];
    const paymentRows = payments.data ?? [];
    return ok({
      period: { from: from_date ?? null, to: to_date ?? null },
      sales_invoice_count: salesRows.length,
      total_sales: sum(salesRows, "net_total"),
      total_purchases: sum(purchases.data ?? [], "net_total"),
      payments_received: sum(
        paymentRows.filter((p) => p.invoice_type === "sales"),
        "amount"
      ),
      payments_made: sum(
        paymentRows.filter((p) => p.invoice_type === "purchase"),
        "amount"
      ),
      unpaid_sales_value: sum(
        salesRows.filter((r) => r.status !== "paid" && r.status !== "cancelled"),
        "net_total"
      )
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ilhfjxmumtvhmfdcmnsg";
var mcp_default = defineMcp({
  name: "iqbook-mcp",
  title: "IQBook",
  version: "0.1.0",
  instructions: "Read-only accounting tools for IQBook. Use `list_clients`, `list_invoices`, `list_items` and `list_vouchers` to inspect the signed-in user's books, and `financial_summary` for totals of sales, purchases, payments and outstanding receivables.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clients_default,
    list_invoices_default,
    list_items_default,
    list_vouchers_default,
    financial_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
